benchmark:
  warmup_iterations: 10
  measured_iterations: 100

models:
  - name: resnet50
    input_shape: [3, 224, 224]
    batch_sizes: [1, 8]
    precision: fp32
  - name: mobilenet_v3
    input_shape: [3, 224, 224]
    batch_sizes: [1, 8]
    precision: fp32
  - name: vgg16
    input_shape: [3, 224, 224]
    batch_sizes: [1, 8]
    precision: fp32
  - name: gpt2
    input_shape: [128]
    batch_sizes: [1, 8]
    precision: fp32

compilers:
  - pytorch_eager
  - torchscript
  - onnxruntime
  - tvm

output:
  format: csv
  save_path: results/
